const level1 = new Level(
  [
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new SmallChicken(),
    new SmallChicken(),
    new Endboss(),
  ],
  [
    new Cloud(0, 0),
    new Cloud(1, 500),
    new Cloud(0, 1000),
    new Cloud(1, 1500),
    new Cloud(0, 2000),
    new Cloud(1, 2500),
    new Cloud(0, 3000),
  ],
  [
    new Coin(400, 100),
    new Coin(800, 100),
    new Coin(1200, 100),
    new Coin(1600, 100),
    new Coin(2000, 100),
    new Coin(2400, 100),
    new Coin(2800, 100),
    new Coin(3200, 100),
  ],
  [new Bottle(500), new Bottle(1000), new Bottle(1500), new Bottle(2000)],
  [
    new backgroundObject("img/5_background/layers/air.png", 0),
    new backgroundObject("img/5_background/layers/3_third_layer/1.png", 0),
    new backgroundObject("img/5_background/layers/2_second_layer/1.png", 0),
    new backgroundObject("img/5_background/layers/1_first_layer/1.png", 0),
    new backgroundObject("img/5_background/layers/air.png", 719),
    new backgroundObject("img/5_background/layers/3_third_layer/2.png", 719),
    new backgroundObject("img/5_background/layers/2_second_layer/2.png", 719),
    new backgroundObject("img/5_background/layers/1_first_layer/2.png", 719),
    new backgroundObject("img/5_background/layers/air.png", 719 * 2),
    new backgroundObject(
      "img/5_background/layers/3_third_layer/1.png",
      719 * 2,
    ),
    new backgroundObject(
      "img/5_background/layers/2_second_layer/1.png",
      719 * 2,
    ),
    new backgroundObject(
      "img/5_background/layers/1_first_layer/1.png",
      719 * 2,
    ),
    new backgroundObject("img/5_background/layers/air.png", 719 * 3),
    new backgroundObject(
      "img/5_background/layers/3_third_layer/2.png",
      719 * 3,
    ),
    new backgroundObject(
      "img/5_background/layers/2_second_layer/2.png",
      719 * 3,
    ),
    new backgroundObject(
      "img/5_background/layers/1_first_layer/2.png",
      719 * 3,
    ),
  ],
);
